coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 0.5%
    changes:
      default:
        target: 80%
        threshold: 0.5%
