name: CI

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest', 'windows-latest' ]
        php-versions: ['8.3']
      fail-fast: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all --strict

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@2.30.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: none
          tools: phpstan, phpunit

      - name: Print PHP Version
        run: echo ${{ steps.setup-php.outputs.php-version }}

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan (Static Analysis)
        run: |
          vendor/bin/phpstan analyse --level max

      - name: Run Unit Tests
        run: vendor/bin/phpunit --configuration phpunit.xml
