name: Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, labeled ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && (github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository) }}

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php: ['8.4']
        experimental: [false]
        include:
          - php: '8.5'
            operating-system: 'ubuntu-latest'
            experimental: true
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@2.34.1
        with:
          php-version: ${{ matrix.php }}
          extensions: intl
          coverage: none
          tools: composer, phpstan, phpunit

      - name: Print PHP Version
        run: echo ${{ steps.setup-php.outputs.php-version }}

      - name: Setup Cache for Composer
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php }}-
            composer-${{ runner.os }}-
            composer-

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all --strict

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        shell: bash

      - name: Security Audit
        run: composer audit

      - name: Run PHPStan (Static Analysis)
        run: composer phpstan

      - name: Run Unit Tests
        run: composer phpunit

      - name: Upload Build Artifact
        if: ${{ matrix.php == '8.3' }}
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.php }}
          path: src/
